# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SXOCProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SXOCProject

  pod 'MJExtension'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'MGJRouter'

end
